// This file is automatically generated. Do not modify it manually.
import type { FirebaseOptions } from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyAHrkUUbl97f_p3NR2qiGGRQc-krF0sD8Y",
  authDomain: "rdc-students-planner-463906.firebaseapp.com",
  projectId: "rdc-students-planner-463906",
  storageBucket: "rdc-students-planner-463906.appspot.com",
  messagingSenderId: "844189707171",
  appId: "1:844189707171:web:34811a014d359e7ca0c816",
  measurementId: "G-JQPXXT5L1R"
};
